name: .NET test
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3.5.3
      with:
        sparse-checkout: csharp_app/
  
    - name: list files
      run: ls -la

    - name: Setup .NET core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.101

    - name: Build project
      run: dotnet build 
