name: .NET test
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3.5.3
  
    - name: list files
      run: ls -la

    - name: Setup .NET core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore Dependencies
      run: dotnet restore main.cs

    - name: Build project
      run: dotnet build main.cs
