# ref: https://github.com/slsa-framework/slsa-verifier#verification-of-provenance
name: slsa-verifier-test
on:
  workflow_dispatch:

jobs:
  verify:
  runs-on: ubuntu-latest
  steps: 
    - name: install slsa-verifier
      uses: slsa-framework/slsa-verifier/actions/installer@v2.3.0

    - name: verify provenance
      run: 
        slsa-verifier verify-artifact flask_app \
        --provenance-path flask_app.intoto.json1 \
        --source-uri gtihub.com/h3samayoa/slsa-demo \
        --source-branch main
        --source-tag v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
